var CapsuleCard = {
  generateAgentCard: function(capsule) {
    if (!capsule) return 'No capsule found.';
    var staple = StapleManifest.manifest;
    return [
      '# Agent Card: ' + capsule.name,
      '',
      '## Intended Use',
      capsule.intendedUse,
      '',
      '## Limitations',
    ].concat(capsule.limitations.map(function(l) { return '- ' + l; }))
    .concat([
      '',
      '## Model / Runtime',
      '- **Model:** `' + capsule.model + '`',
      '- **Runtime:** ' + capsule.runtime,
      '- **Architecture:** ' + capsule.arch,
      '- **Mode:** ' + capsule.mode,
      '',
      '## Data / Memory Policy',
    ].concat(capsule.memoryRules.map(function(r) { return '- ' + r; }))
    .concat([
      '',
      '## Permissions',
    ].concat(capsule.permissions.map(function(p) { return '- ' + p; }))
    .concat([
      '',
      '## Eval Commands',
    ].concat(capsule.evals.map(function(e) { return '- `' + e + '`'; }))
    .concat([
      '',
      '## Woz Vault Seal',
      '```',
      capsule.seal || 'none',
      '```',
      '',
      '## Repo Staple',
      staple ? '- **Repo:** ' + staple.repo + '\n- **Version:** ' + staple.version + '\n- **Page Seal:** `' + staple.pageSeal + '`' : '- No staple available',
      '',
      '---',
      '*Generated by Apple II Universal Machine · Browser-safe simulation · Not real model training*'
    ]))));
  },

  generateTwinCard: function(twin) {
    if (!twin) return 'No twin found.';
    return [
      '# Digital Twin Card: ' + twin.name,
      '',
      '## Role',
      twin.role,
      '',
      '## Personality',
      twin.personality || 'methodical',
      '',
      '## Memory Rules',
    ].concat((twin.memoryRules || []).map(function(r) { return '- ' + r; }))
    .concat([
      '',
      '## Permissions',
    ].concat((twin.permissions || []).map(function(p) { return '- ' + p; }))
    .concat([
      '',
      '## Seal',
      '```',
      twin.seal || 'none',
      '```',
      '',
      '---',
      '*Generated by Apple II Universal Machine · Browser-safe simulation*'
    ])));
  },

  generateModelCard: function(capsule) {
    if (!capsule) return 'No capsule found.';
    return [
      '# Model Card: ' + capsule.name,
      '',
      '## Architecture',
      capsule.arch,
      '',
      '## Base Model',
      capsule.model,
      '',
      '## Runtime',
      capsule.runtime,
      '',
      '## Intended Use',
      capsule.intendedUse,
      '',
      '## Limitations',
    ].concat(capsule.limitations.map(function(l) { return '- ' + l; }))
    .concat([
      '',
      '## Training Status',
      '**SIMULATED** — No real model training has occurred.',
      'This is a packaging and verification system, not a training pipeline.',
      '',
      '## Seal',
      '```',
      capsule.seal || 'none',
      '```',
      '',
      '---',
      '*Generated by Apple II Universal Machine · Not real model training*'
    ]));
  },

  downloadCard: function(content, filename) {
    var blob = new Blob([content], { type: 'text/markdown' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    return filename;
  }
};
